spring:
  application:
    name: api_rest_senaclick

  datasource:
    url: jdbc:mysql://localhost:3306/senaclick
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        globally_quoted_identifiers: true

  output:
    ansi:
      enabled: ALWAYS

  logging:
    level:
      org.springframework.boot.context: DEBUG

server:
  port: 8081